[versions]
activity = "1.12.2"
agp = "8.13.2"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
kotlin = "2.3.0"
material = "1.13.0"
navigationFragments = "1.2.4"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
hotwire-native-core = { module = "dev.hotwire:core", version.ref = "navigationFragments" }
hotwire-native-navigation = { module = "dev.hotwire:navigation-fragments", version.ref = "navigationFragments" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
